[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "elrs_simulator"
version = "0.1.0"
description = "ExpressLRS Physical Layer and FHSS Simulator"
dependencies = [
    "numpy",
    "matplotlib",
    "scipy"
]